name: eShopOnWeb Build and Test

# Triggers (uncomment line below to use it)
on: workflow_dispatch

# Environment variables
env:
  RESOURCE-GROUP: rg-eshoponweb-eastus
  LOCATION: westeurope
  TEMPLATE-FILE: infra/webapp.bicep
  SUBSCRIPTION-ID: 751977a7-b891-408a-9e0c-e57b0e5ece10
  WEBAPP-NAME: devops-webapp-eastus-235094704

jobs:
  # Build, test and publish .net web project in repository
  buildandtest:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v2
      
      # Setup .NET environment
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '6.0.x'
      
      # Build/Test/Publish the .NET project
      - name: Build with dotnet
        run: dotnet build ./eShopOnWeb.sln --configuration Release
      - name: Test with dotnet
        run: dotnet test ./eShopOnWeb.sln --configuration Release
      - name: dotnet publish
        run: |
          dotnet publish ./src/Web/Web.csproj -c Release -o ${{env.DOTNET_ROOT}}/myapp
          zip -r app.zip ${{env.DOTNET_ROOT}}/myapp
      
      # Upload the published website code artifacts
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: .net-app
          path: app.zip
        
      # Upload the Bicep template as artifacts for next job
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: bicep-template
          path: ${{ env.TEMPLATE-FILE }}

  # Use Bicep to deploy infrastructure + Publish webapp 
  deploy:
    runs-on: ubuntu-latest
    needs: buildandtest
    environment:
      name: 'Development'
    steps:
      # Download the publish files created in previous job
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: .net-app
          path: .net-app
  
      # Download the Bicep templates from previous job
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: bicep-template
          path: bicep-template
        
      # Login in your Azure subscription using a service principal (credentials stored as GitHub Secret in repo)
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
           
      # Deploy Azure WebApp using Bicep file
      - name: Deploy
        run: |
          az deployment sub create --location ${{ env.LOCATION }} --template-file ${{ env.TEMPLATE-FILE }} --parameters webAppName=${{ env.WEBAPP-NAME }} location=${{ env.LOCATION }} --subscription ${{ env.SUBSCRIPTION-ID }}

